const menuItems = [
  {
    id: 1,
    name: {
      en: "Borscht",
      ar: "بورشت",
      ru: "Борщ",
    },
    description: {
      short: {
        en: "A traditional Russian dish with tender meat and rich sauce.",
        ar: "وجبة بورشت الروسية التقليدية مع لحم مطهي وsauce غني",
        ru: "Традиционный русский блюдo с мясом и богатым соусом.",
      },
      long: {
        en: "A traditional Russian dish with tender meat and rich sauce.",
        ar: "وجبة بورشت الروسية التقليدية مع لحم مطهي وsauce غني",
        ru: "Традиционный русский блюдo с мясом и богатым соусом.",
      },
    },
    price: 10.99,
    images: {
      thumbnail: borscht,
      full: borscht,
    },
    nutrition: {
      calories: 100,
      protein: 10,
      fat: 10,
      carbs: 10,
    },
    ingredients: [
      "beef",
      "potatoes",
      "carrots",
      "onions",
      "garlic",
      "salt",
      "pepper",
    ],
  },
];
