import RussianFlag from "./russia_flag.svg";
import BritishFlag from "./uk_flag.svg";
import ArabicFlag from "./saudi_flag.svg";
// WebP, generated by scripts/convertMenuImagesToWebp.mjs. As a JPEG this was
// 1.55 MB and it is the homepage LCP element.
import heroBackground from "./images/hero-background.webp";

export { RussianFlag, BritishFlag, ArabicFlag, heroBackground };
export * from "./dishPlaceholder.js";
export * from "./menuItems/menuItemExports.js";
export * from "./socialLogos/_socialLogos.index.js";
export * from "./aggregatorLogos/_aggregatorLogos.index.js";
